### ISSUE TITLE
0.9.5 fails due to undefined sassPath (and cssPath)

### ISSUE THREAD

**Issue by cofiem** [sass/node-sass-middleware#58] opened 2015-09-16 10:58 UTC
express.js server error

````
$ DEBUG=myapp npm start

> phd-prototypes@0.0.0 start /home/me/myapp
> node ./bin/www

  read: undefined
GET / 500 489.753 ms - 1119
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
    at ServerResponse.header (/home/me/myapp/node_modules/express/lib/response.js:718:10)
    at ServerResponse.send (/home/me/myapp/node_modules/express/lib/response.js:163:12)
    at done (/home/me/myapp/node_modules/express/lib/response.js:957:10)
    at Object.exports.renderFile (/home/me/myapp/node_modules/jade/lib/index.js:374:12)
    at View.exports.__express [as engine] (/home/me/myapp/node_modules/jade/lib/index.js:417:11)
    at View.render (/home/me/myapp/node_modules/express/lib/view.js:126:8)
    at tryRender (/home/me/myapp/node_modules/express/lib/application.js:639:10)
    at EventEmitter.render (/home/me/myapp/node_modules/express/lib/application.js:591:3)
    at ServerResponse.render (/home/me/myapp/node_modules/express/lib/response.js:961:7)
`````

express.js client error

````
TypeError: path must be a string
    at TypeError (native)
    at Object.fs.exists (fs.js:210:11)
    at compile (/home/me/myapp/node_modules/node-sass-middleware/middleware.js:223:10)
    at sass (/home/me/myapp/node_modules/node-sass-middleware/middleware.js:248:14)
    at Layer.handle [as handle_request] (/home/me/myapp/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/me/myapp/node_modules/express/lib/router/index.js:312:13)
    at /home/me/myapp/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/me/myapp/node_modules/express/lib/router/index.js:330:12)
    at next (/home/me/myapp/node_modules/express/lib/router/index.js:271:10)
    at cookieParser (/home/me/myapp/node_modules/cookie-parser/index.js:48:5)

**Comment by cofiem** [comment] 2015-09-16 11:20
This problem occurred without any changes to my project's code. I only did `npm update`.

Further, I was able to reproduce this issue with a new express js project.

Steps:

1. `mkdir test-nsm`
1. `cd ./test-nsm`
1. `npm init (all defaults)`
1. `npm install express --save`
1. `npm install express-generator -g`
1. `cd ../`
1. `express test-nsm`
1. `cd ./test-nsm`
1. `npm install`
1. `npm install node-sass-middleware --save`
1. edit ./app.js to add:
````
var express = require('express');
var sassMiddleware = require('node-sass-middleware');

app.use(cookieParser());
// sass compiling
app.use(sassMiddleware({
	src: path.join(__dirname, 'public', 'stylesheets'),
	dest: path.join(__dirname, 'public', 'stylesheets'),
	debug: true,
	outputStyle: 'compressed'
}));
````
1. `DEBUG=test-nsm npm start`
1. open localhost:3000 in a browser

**Comment by am11** [comment] 2015-09-16 13:19
Thanks for reporting this. Some recent refactoring is the cause, but undetectable by our tests.
Could you submit a test case which test this scenario; in order to avoid such regression in future?

**Comment by vanm** [comment] 2015-09-16 18:48
This is pretty urgent to get merged and pushed to NPM.  It prevented all assets from rendering in my app until I tracked it down to this module and reverted to 0.9.0.  Teaches me for using the `^`

**Comment by am11** [comment] 2015-09-16 18:50
v0.9.6 is released with the fix. 

@vanm, :)

**Closed by am11** 2015-09-16 18:50 UTC

**Comment by vanm** [comment] 2015-09-16 18:52
Thanks! ;)

**Comment by cofiem** [comment] 2015-09-17 00:47
Thanks very much for the quick fix!
